linux: adjust amdgpufb patch, but errors out on missing reference.
ld: vmlinux.o: in function `amdgpufb_create':
amdgpu_fb.c:(.text+0x4b6156): undefined reference to `amdgpu_display_gem_fb_init'

needs looking into